sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gnQuZT+ZIPVTOF/Zgg08cVcySV6oUbG6HsnaW5Fp7YsKCitGH95XmFZePVOjqoWgQdgmt3gSABgkaPZwHh6satmqheS6Q2Yw1gRmI2vMFVTaW/ex2IOdsTsjnpjHDVOtdMNr/YqLU57wOuH5CD4s441KCiS5T2/2ub848ZnnXYOO3KQhqF/apbHB3CZcoY90laomWivKsccdjyvcIGcpFbXYFPvrrBvbjDKiR7ReSONAIeGiLnCdFZe5pNenL5Z6jTpYZkcQ9HraCF5gWg0dZvkN1Ce/635lF+DVviPuB1XlZ8xm1WWge7jph3+HVB6H5+fhjghnqY0Dgw118HPynZtSEijoJVANSNh1Q94mo2WJJ10nZCbhASRRxhUUzWovTGwImu8XGzwqB4HB6zWFiktv4IENAVQDo7cggrz7tXWrJsOKGW/Z7mkMqXV1mx/3SQQHNJz8QVhbLcdal/J5DswlQ3VNw7TskvAS7FsXg31ibhrfNRVFfkCer9itOTR8JfGW0T0b+kY5rIvdy3IQbrpN5je/ozr/7m0SpHyzEy9i+Hyrtzci/Yyoe/kBGqazbsWU0TkHcnDAS/w0MhIkT2OI9Qxbi1M9kTelX+GH/6CovCjcdeD2Dl1Qkc9uv5r4CMsfoydllR2Lp2QSEoEdcXLvvdSHdY6dEhChhkvrVcM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Face-Illumined_2501
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy